services:
  - type: web
    name: ai-research-synthesizer
    env: node
    buildCommand: npm run build
    startCommand: serve dist
    staticPublishPath: dist
    envVars:
      - key: GEMINI_API_KEY
        sync: false
